# Generated by Django 4.2.7 on 2023-11-13 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('avatar', models.ImageField(upload_to='doctros-images')),
                ('prefix', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('rank', models.CharField(blank=True, choices=[('HO', 'HOUSE OFFICER'), ('MO', 'MEDICAL OFFICER'), ('SMO', 'SENIOR MEDICAL OFFICER'), ('PMO', 'PRINCIPAL MEDICAL OFFICER'), ('PHY', 'CONSULTANT PHYSICIAN'), ('SURG', 'CONSULTANT SURGEON')], max_length=4, null=True)),
                ('specialty', models.CharField(blank=True, choices=[('CARD', 'CARDIOLOGY'), ('NEURO', 'NEUROLOGY'), ('GI', 'GASTROENTEROLOGY'), ('RENAL', 'NEPHROLOGY'), ('RS', 'PULMONOLOGIST'), ('ENDO', 'ENDOCRINOLOGY'), ('GS', 'GENERAL SURGEON'), ('PS', 'PAEDIATRIC SURGEON'), ('URO', 'UROLOGIST'), ('ORTHO', 'ORTHOPAEDIC SURGEON'), ('PLASTIC', 'PLASTIC SURGEON'), ('NS', 'NEUROSURGEON'), ('O $ G', 'oBSTETRICS AND GYNAECOLOGY'), ('ENT', 'ENT SURGEON'), ('EYE', 'OPHTHALMOLOGY'), ('OTHERS', 'OTHERS')], max_length=7, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
